11_public_web_beranda
aldhisttd/5pagib_cafe_template pull request #16
Opened 2023-12-09 10:57 UTC by AngelinaPaskah

2023-12-09 13:08 UTC, aldhi88 requested changes
@AngelinaPaskah bagian menu atas nya salah, baca instruksi ya

2023-12-09 15:12 UTC, aldhi88 requested changes
@AngelinaPaskah , baca revisi saya sebelumnya

2023-12-09 16:26 UTC, AngelinaPaskah commented
Ini hasil perbaikannya pak
![Screenshot (26)](https://github.com/aldhisttd/5pagib_cafe_template/assets/129471189/fface7d1-4612-485c-90ff-9c493f816984)
![Screenshot (27)](https://github.com/aldhisttd/5pagib_cafe_template/assets/129471189/5f161622-20c7-4616-b4ee-21838b17bc03)

2023-12-10 07:40 UTC, aldhi88 requested changes
@AngelinaPaskah baca revisinya

2023-12-11 12:25 UTC, closed without merging