mastre dasboard
aldhisttd/5pagib_cafe_template pull request #17
Opened 2023-12-09 14:12 UTC by putriEkaOktaPiya

2023-12-09 14:21 UTC, putriEkaOktaPiya commented
<img width="960" alt="Screenshot 2023-12-09 092410" src="https://github.com/aldhisttd/5pagib_cafe_template/assets/129470923/5afc116a-ef2a-4784-82ca-76fdf72a6202">

2023-12-09 15:01 UTC, aldhi88 requested changes
@putriEkaOktaPiya , menu di kiri nya gak sesuai dengan deskripsi yang saya instruksikan di card nya

2023-12-09 15:33 UTC, putriEkaOktaPiya commented
> @putriEkaOktaPiya ,

2023-12-10 03:56 UTC, aldhi88 approved these changes

2023-12-10 03:56 UTC, merged