15. form input kategori
aldhisttd/5pagib_cafe_template pull request #19
Opened 2023-12-09 15:29 UTC by sitiannisaa

<img width="960" alt="Screenshot 2023-12-09 222853" src="https://github.com/aldhisttd/5pagib_cafe_template/assets/129470849/92230b85-af2d-4481-92ba-e7cec7405ed1">

2023-12-10 09:07 UTC, aldhi88 requested changes
@sitiannisaa 

Posisi konten nya kok rapat2 gini ya kurang rapi, liad contoh konten nya di example bottstrap

2023-12-10 09:46 UTC, aldhi88 requested changes
@sitiannisaa , card kamu cuma form aja, tidak ada table,
penataan konten nya masih kurang rapi, lihat hasil konten card nomor 17

2023-12-10 11:04 UTC, sitiannisaa commented
<img width="960" alt="Screenshot 2023-12-10 180311" src="https://github.com/aldhisttd/5pagib_cafe_template/assets/129470849/682afc4f-002d-44ab-98b1-8e25e1fd05c3">

2023-12-11 03:43 UTC, aldhi88 requested changes

2023-12-11 03:43 UTC, aldhi88 commented on admin/menu_input.html
> +                <div class="  alert alert-secondary  ">
@sitiannisaa , jangan dibungkus dengan alert secondary, saya mau tidak ada background abu-abunya

2023-12-11 04:28 UTC, sitiannisaa commented
<img width="960" alt="Screenshot 2023-12-11 112739" src="https://github.com/aldhisttd/5pagib_cafe_template/assets/129470849/fdf83415-2be5-4770-b6d8-64d94d0a4218">

2023-12-11 05:36 UTC, aldhi88 approved these changes

2023-12-11 05:36 UTC, merged